apiVersion: v1
kind: Pod
metadata:
  name: redis-1
spec:
  containers:
  - name: redis-1
    image: redis
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["3000"]
  nodeSelector:
    kubernetes.io/hostname: ip-10-20-1-157.us-west-2.compute.internal
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-2
spec:
  containers:
  - name: redis-2
    image: redis
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["3000"]
  nodeSelector:
    kubernetes.io/hostname: ip-10-20-1-182.us-west-2.compute.internal
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-3
spec:
  containers:
  - name: redis-3
    image: redis
    imagePullPolicy: IfNotPresent
    command: ["sleep"]
    args: ["3000"]
  nodeSelector:
    kubernetes.io/hostname: ip-10-20-2-18.us-west-2.compute.internal
