apiVersion: v1
kind: Pod
metadata:
  name: test-tmp
  namespace: kube-system
spec:
  containers:
  - name: test-tmp
    image: cosmintitei/bash-curl
    resources:
      requests:
        cpu: "800m"
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["sleep", "600"]
  nodeSelector:
    eks-compute-type: cpu
