name: PrepareEnvironment
definition:
  StartAt: DryRun
  States:
    DryRun:
      Type: Choice
      Choices:
        - Variable: "$.input.dry_run"
          BooleanEquals: true
          Next: Succeed
      Default: Run
    Run:
      Type: Task
      Parameters:
        input.$: "$.input"
      Resource:
        Fn::GetAtt: [Sub2Function, Arn]
      ResultPath: "$.output.run"
      Next: Succeed
    Succeed:
      Type: Succeed
